version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - redis
    volumes:
      - /home/ubuntu/rate-website:/usr/share/nginx/html
  redis:
    image: redis:latest