---
- name: rateupdate Service enable
  systemd:
    name: rateupdate.service
    state: started
    enabled: yes

- name: rateupdate Timer enable
  systemd:
    name: rateupdate.timer
    state: started
    enabled: yes
