---
- name: Make sure nginx is the latest version
  apt:
    name: nginx
    state: latest
- name: Make sure nginx is running
  systemd:
    state: started
    name: nginx
    enabled: yes
- name: copy the index.html
  copy:
    src: /home/ubuntu/resources/rate-website/source/index.html
    dest: /var/www/rate-website/
    remote_src: true
- name: change ownership and file permissions for index.html
  file:
    dest: /var/www/rate-website/
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
    recurse: yes
- name: copy the nginx config file and restart nginx
  copy:
    src: /home/ubuntu/resources/rate-website/rate-website.cfg
    dest: /etc/nginx/sites-available/
    remote_src: true
- name: create symlink
  file:
    src: /etc/nginx/sites-available/rate-website.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
- name: restart nginx
  service:
    name: nginx
    state: restarted