---
- name: Make sure nginx is the latest version
  apt:
    name: nginx
    state: latest

- name: Make sure nginx is running
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: create website folder 
  file:
    path: /var/www/rate-website/
    state: directory
    mode: '0755'
    recurse: yes

- name: create the index.html
  file:
    path: /var/www/rate-website/index.html
    state: touch
    mode: u=rw,g=r,o=r

- name: copy the nginx config file
  copy:
    src: config/
    dest: /etc/nginx/sites-available/

- name: create symlink
  file:
    src: /etc/nginx/sites-available/rate-website.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
