name: Terraform

# on:
#   workflow_run:
#     workflows: ["Packer"]
#     branches:
#       - "main"
#     types:
#       - completed

on:
  push:
    branches:
      - "main"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check terraform/
        env:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Terraform Init
        id: init
        run: terraform init terraform/

      - name: Terraform Plan
        id: plan
        run: terraform plan terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve terraform/